- name: Add keepassxc repository
  apt_repository:
    repo: ppa:phoerious/keepassxc
  tags:
    - packages
    - ui

- name: Install basic UI tools
  become: yes
  apt:
    state: latest
    name:
    - keepassxc
    - vlc
    - meld
  tags:
    - packages
    - ui
