- name: Add keepassxc repository
  apt_repository:
    repo: ppa:phoerious/keepassxc
  tags:
    - packages
    - ui

- name: Install basic UI tools
  become: yes
  apt:
    state: latest
    name:
    - keepassxc
    - vlc
    - meld
    - copyq
    - copyq-plugins
    - flameshot
  tags:
    - packages
    - ui

- name: Autostart CopyQ
  copy:
    src: roles/basic-ui-tools/files/copyq.desktop
    dest: ~/.config/autostart/
  tags:
    - ui

- name: Setup flameshot keyboard shortcut
  shell: 'dconf load / < roles/basic-ui-tools/files/flameshot-keyboard-shortcut.ini'
  args:
    warn: False
  tags:
    - ui