---
- hosts: all
  connection: local
  module_defaults:
    apt:
      cache_valid_time: 3600
  roles:
    - shell
    - basic-tools
    - dotfiles
    - docker
    - guake
    - java
    - git
    - basic-ui-tools
