- name: Link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/dotfiles/vim/.SpaceVim", dest: "~/.SpaceVim"}
    - { src: "~/dotfiles/vim/.SpaceVim.d", dest: "~/.SpaceVim.d"}
    - { src: "~/.SpaceVim", dest: "~/.vim"}
    - { src: "~/dotfiles/zsh/.bash_aliases", dest: "~/.bash_aliases"}
    - { src: "~/dotfiles/zsh/.exports", dest: "~/.exports"}
    - { src: "~/dotfiles/git/.gitconfig", dest: "~/.gitconfig"}
    - { src: "~/dotfiles/git/.gitconfig-private", dest: "~/.gitconfig-private"}
    - { src: "~/dotfiles/git/.gitconfig-neo4j", dest: "~/.gitconfig-neo4j"}
    - { src: "~/dotfiles/git/.gitignore_global", dest: "~/.gitignore_global"}
    - { src: "~/dotfiles/tmux/.tmux.conf", dest: "~/.tmux.conf"}
    - { src: "~/.zprezto/runcoms/zlogin", dest: "~/.zlogin"}
    - { src: "~/.zprezto/runcoms/zlogout", dest: "~/.zlogout"}
    - { src: "~/.zprezto/runcoms/zpreztorc", dest: "~/.zpreztorc"}
    - { src: "~/.zprezto/runcoms/zshenv", dest: "~/.zshenv"}
    - { src: "~/.zprezto/runcoms/zshrc", dest: "~/.zshrc"}
  tags: dotfiles