---
- name: Verify if jabba is installed
  stat:
    path: "~/.jabba/"
  register: "jabba_installed"
  tags:
    - java

- name: Install jabba
  shell: 'curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash'
  args:
    warn: False
  when: not jabba_installed.stat.exists
  tags:
    - java

- name: Install Java
  shell: '. ~/.jabba/jabba.sh && jabba install $(jabba ls-remote | grep adopt@1.{{item}} | head -n 1)'
  args:
    warn: False
  with_items:
    - 11
    - 15
  tags:
    - java

- name: Set default Java version to {{default_java_version}}
  shell: '. ~/.jabba/jabba.sh && jabba alias default $(jabba ls | grep adopt@1.{{default_java_version}} | head -n 1)'
  args:
    warn: False
  tags:
    - java
